INPUTFILE = 'download/data.csv'
OUTPUTJSON = 'result/geodata.geojson'
DATAPATH = '/data'
OUTPUTCSV = 'result/geodata.csv'
URLTS = 'https://docs.google.com/spreadsheets/d/1UF2pSkFTURko2OvfHWWlFpDFAr1UxCBA4JLwlSP6KFo/export?format=csv'
DELIMITER = ','